name: Rust build and test

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings" # Fail compilation on any warnings

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --all-features --verbose

      - name: Check formatting
        run: cargo fmt --check
